apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: self-supervised-mn-job$jobidx-commit$trunc_hash
  labels:
    lpnet: multi-node-job$jobidx-commit$trunc_hash
spec:
  selector: 
    matchLabels:
      lpnet: multi-node-job$jobidx-commit$trunc_hash
  serviceName: mn-job$jobidx-commit$trunc_hash
  replicas: $total
  template:
    metadata:
      labels:
        lpnet: multi-node-job$jobidx-commit$trunc_hash
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: clone-repo
        image: shubhamkulkarni01/lpnet:original_pytorch
        resources:
          limits:
            memory: 24Gi
            cpu: 12
            ephemeral-storage: 100Gi
          requests:
            memory: 24Gi
            cpu: 12
            ephemeral-storage: 100Gi
        command: ["/bin/bash", "-c"]
        args: 
            ["cd /opt/repo && \
              git clone 'https://gitlab.nrp-nautilus.io/skulkarn/lpnet-self-supervised.git' && \
              git -C lpnet-self-supervised checkout $git_hash "]
        volumeMounts:
        - mountPath: /tempdir
          name: newawsmount
        - mountPath: /awsmount
          name: inputdata
        - mountPath: /opt/repo
          name: gitrepo
        - mountPath: /data/out
          name: datablock
      containers:
      - name: train-model
        image: shubhamkulkarni01/lpnet:original_pytorch
        env:
          - name: WANDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: wandb-key-secret
                key: WANDB_API_KEY
        resources:
          limits:
            memory: 32Gi
            cpu: 12
            nvidia.com/gpu: 1
            ephemeral-storage: 100Gi
          requests:
            memory: 32Gi
            cpu: 12
            nvidia.com/gpu: 1
            ephemeral-storage: 100Gi
        command: ["/bin/bash", "-c"]
        args: ["pip install wandb && \
                conda list &&  \
                cd /opt/repo/lpnet-self-supervised && \
                python3 prepare_data.py $jobidx && \
                mkdir -p /data/out/rendezvous && \
                rm -rf /data/out/rendezvous/job$jobidx-commit$trunc_hash && \
                LOGLEVEL=DEBUG torchrun \
                  --nnodes=$total \
                  --nproc_per_node=1 \
                  --max_restarts=4 \
                  --rdzv_id=job-$jobidx \
                  --rdzv_backend=c10d \
                  --rdzv_endpoint=self-supervised-mn-job$jobidx-commit$trunc_hash-0.mn-job$jobidx-commit$trunc_hash.guru-research.svc.cluster.local \
                  --rdzv_conf join_timeout=600,timeout=600 \
                  main.py $jobidx
        "]
        volumeMounts:
        - mountPath: /newawsmount
          name: newawsmount
        - mountPath: /data/out
          name: datablock
        - mountPath: /opt/repo
          name: gitrepo
        - mountPath: /awsmount
          name: inputdata
        - mountPath: /dev/shm
          name: dshm
      volumes:
        - name: datablock
          persistentVolumeClaim:
            claimName: lpnet-self-supervised-output-data
        - name: gitrepo
          emptyDir: {}
        - name: newawsmount
          persistentVolumeClaim:
            claimName: lpnet-self-supervised-input-data
        - name: dshm
          emptyDir:
            medium: Memory
        - name: inputdata
          emptyDir: 
            medium: Memory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                      # - NVIDIA-A100-PCIE-40GB-MIG-2g.10gb
                    - NVIDIA-A100-SXM4-80GB
                      # - NVIDIA-RTX-A6000
                    - NVIDIA-A10
                    - NVIDIA-A40
                      # - NVIDIA-GeForce-RTX-3090
                      # - NVIDIA-TITAN-Xp
                      # - NVIDIA-TITAN-RTX
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - hcc-nrp-shor-c5909.unl.edu
