apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lpnet-self-supervised-input-data
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
