apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lpnet-self-supervised-output-data
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
